name: baseline
project: sssupervised
version: null
offline: false

seed: 69
checkpoint_period: 50
lr_find: false

dataset: cifar
dataset_path: data
n_labeled: 400
n_overlap: 4

width: 2
lr: 0.01
wd: 0.0005
smoothing: 0.0
batch_size: 128
randaug_n: 3
randaug_m: 9

trainer:
  gpus: 1
  max_steps: 100000
  check_val_every_n_epoch: 50
