name: baseline
project: sssupervised
version: null
offline: false

seed: 69
checkpoint_period: 100
lr_find: false

data_path: data
n_labeled: 400
n_overlap: 4

width: 2
lr: 0.05
wd: 0.0001
smoothing: 0.1
batch_size: 128
randaug_n: 3
randaug_m: 12

trainer:
  gpus: 1
  max_steps: 100000
