name: baseline_quickdraw
project: sssupervised
version: null
offline: false

seed: 69
checkpoint_period: 50
lr_find: false

dataset: quickdraw
dataset_path: data
n_labeled: 1000
n_overlap: 10

width: 2
lr: 0.01
wd: 0.0005
smoothing: 0.0
batch_size: 64


trainer:
  gpus: 1
  max_steps: 100000
  check_val_every_n_epoch: 50
