name: contrastive_qd
project: contrastive
version: null
offline: false
wandb: false
lr_find: false

checkpoint_period: 10
seed: 69

dataset: quickdraw
dataset_path: data
n_labeled: 100
n_overlap: 10

width: 2
lr: 0.005
wd: 0.0005
batch_size: 256
queue_size: 4096
temperature: 0.5

trainer:
  gpus: 1
  max_steps: 50000
  check_val_every_n_epoch: 10
