name: contrastive_pretrain
project: contrastive
version: null
offline: false
wandb: true
lr_find: false

checkpoint_period: 20
seed: 69

dataset: cifar
dataset_path: data
n_labeled: 400
n_overlap: 4

width: 2
lr: 0.05
wd: 0.0005
batch_size: 128
queue_size: 4096
temperature: 0.07
randaug_n: 3
randaug_m: 9

trainer:
  gpus: 1
  max_steps: 100000
  check_val_every_n_epoch: 10
