name: uda_quickdraw
project: sssupervised
version: null
offline: false
lr_find: false

checkpoint_period: 20
seed: 69

dataset: quickdraw
dataset_path: data
n_labeled: 100
n_overlap: 10

width: 2
lr: 0.003
wd: 0.0005
batch_size_l: 64
batch_size_u: 128
uda_tsa: False
uda_loss_weight: 1
uda_softmax_temp: 0.4
uda_confidence_threshold: 0.8

trainer:
  gpus: 1
  max_steps: 50000
  check_val_every_n_epoch: 100
